apiVersion: apps/v1
kind: Deployment
metadata:
  name: bata-shoes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bata-shoes
  template:
    metadata:
      labels:
        app: bata-shoes
    spec:
      containers:
        - name: bata-shoes
          image: <your-dockerhub-username>/bata-shoes:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bata-shoes-service
spec:
  type: NodePort
  selector:
    app: bata-shoes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
